version: '3'
volumes:
  mydb:
services:
  web:
    restart: always
    build: .
    container_name: dj_api
    command: bash -c "cd src && python manage.py makemigrations && python manage.py migrate --noinput &&  python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:latest
    container_name: db_carambolo
    volumes:
      - mydb:/var/lib/postgresql/data
    expose:
      - 5432
    restart: always