# Generated by Django 2.2.5 on 2019-09-07 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2019, 9, 7)),
        ),
        migrations.AddField(
            model_name='mood',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mood',
            name='racional_thought',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mood',
            name='thought',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mood',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mood',
            name='feeling',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
